-- =============================================================================
-- MyFoodOrdering — Script SQL unique
-- À exécuter UNE SEULE FOIS dans Supabase → SQL Editor → New query
--
-- Sections :
--   1. Extensions
--   2. Tables
--   3. Index
--   4. Trigger (profil auto à l'inscription)
--   5. Row Level Security
--   6. Storage (bucket plats + politiques)
--   7. Données initiales (menu luxe)
--   8. Notes de configuration
-- =============================================================================


-- =============================================================================
-- 1. EXTENSIONS
-- =============================================================================

create extension if not exists "uuid-ossp";


-- =============================================================================
-- 2. TABLES
-- =============================================================================

-- Profils utilisateurs (liés à auth.users)
create table if not exists public.profiles (
  id        uuid primary key references auth.users (id) on delete cascade,
  nom       text not null default '',
  email     text not null default '',
  telephone text,
  role      text not null default 'user',
  adresse   text
);

-- Catégories de plats
create table if not exists public.categories (
  id   bigint generated by default as identity primary key,
  nom  text   not null,
  emoji text
);

-- Plats du menu
create table if not exists public.plats (
  id          bigint generated by default as identity primary key,
  nom         text             not null,
  description text             not null default '',
  prix        double precision not null default 0,
  image_url   text,
  categorie_id bigint          not null references public.categories (id)
);

-- Commandes
create table if not exists public.commandes (
  id        bigint generated by default as identity primary key,
  user_id   uuid             not null references auth.users (id),
  total     double precision not null,
  statut    text             not null default 'En attente',
  adresse   text             not null default '',
  telephone text             not null default '',
  date      timestamptz default now()
);

-- Lignes de commande
create table if not exists public.commande_items (
  id          bigint generated by default as identity primary key,
  commande_id bigint           not null references public.commandes (id) on delete cascade,
  plat_id     bigint           not null references public.plats (id),
  quantite    int              not null default 1,
  prix        double precision not null
);

-- Tokens FCM pour notifications push
create table if not exists public.push_tokens (
  id         uuid    primary key default gen_random_uuid(),
  user_id    uuid    not null references auth.users (id) on delete cascade,
  token      text    not null,
  platform   text    not null default 'android',
  updated_at timestamptz not null default now(),
  unique (user_id, token)
);

-- Avis (note 1-5 étoiles, un seul avis par utilisateur par plat)
create table if not exists public.avis (
  id      bigint generated by default as identity primary key,
  plat_id bigint not null references public.plats (id)  on delete cascade,
  user_id uuid   not null references auth.users (id)    on delete cascade,
  note    int    not null check (note between 1 and 5),
  date    timestamptz default now(),
  unique (plat_id, user_id)
);

-- Favoris (un favori par utilisateur par plat)
create table if not exists public.favoris (
  id         bigint generated by default as identity primary key,
  user_id    uuid   not null references auth.users (id) on delete cascade,
  plat_id    bigint not null references public.plats (id) on delete cascade,
  created_at timestamptz default now(),
  unique (user_id, plat_id)
);


-- =============================================================================
-- 3. INDEX
-- =============================================================================

create index if not exists idx_commandes_user_id         on public.commandes (user_id);
create index if not exists idx_commande_items_commande_id on public.commande_items (commande_id);
create index if not exists idx_push_tokens_user_id        on public.push_tokens (user_id);
create index if not exists idx_avis_plat_id               on public.avis (plat_id);
create index if not exists idx_favoris_user_id            on public.favoris (user_id);


-- =============================================================================
-- 4. TRIGGER — Création automatique du profil à l'inscription
-- =============================================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, nom, email)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'nom', ''),
    coalesce(new.email, '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function public.handle_new_user();


-- =============================================================================
-- 5. ROW LEVEL SECURITY
-- =============================================================================

alter table public.profiles      enable row level security;
alter table public.categories    enable row level security;
alter table public.plats         enable row level security;
alter table public.commandes     enable row level security;
alter table public.commande_items enable row level security;
alter table public.push_tokens   enable row level security;
alter table public.avis          enable row level security;
alter table public.favoris       enable row level security;

-- Nettoyage des anciennes politiques
drop policy if exists "categories_select_public"   on public.categories;
drop policy if exists "categories_admin_all"        on public.categories;
drop policy if exists "plats_select_public"         on public.plats;
drop policy if exists "plats_admin_insert"          on public.plats;
drop policy if exists "plats_admin_update"          on public.plats;
drop policy if exists "plats_admin_delete"          on public.plats;
drop policy if exists "profiles_select_own"         on public.profiles;
drop policy if exists "profiles_update_own"         on public.profiles;
drop policy if exists "profiles_insert_own"         on public.profiles;
drop policy if exists "commandes_select"            on public.commandes;
drop policy if exists "commandes_insert"            on public.commandes;
drop policy if exists "commandes_update_admin"      on public.commandes;
drop policy if exists "commande_items_select"       on public.commande_items;
drop policy if exists "commande_items_insert"       on public.commande_items;
drop policy if exists "push_tokens_own_all"         on public.push_tokens;
drop policy if exists "avis_select_public"          on public.avis;
drop policy if exists "avis_insert_own"             on public.avis;
drop policy if exists "avis_update_own"             on public.avis;
drop policy if exists "avis_delete_own"             on public.avis;
drop policy if exists "favoris_select_own"          on public.favoris;
drop policy if exists "favoris_insert_own"          on public.favoris;
drop policy if exists "favoris_delete_own"          on public.favoris;

-- ── Catégories ────────────────────────────────────────────────────────────────
create policy "categories_select_public" on public.categories
  for select using (true);

create policy "categories_admin_all" on public.categories
  for all
  using   (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

-- ── Plats ─────────────────────────────────────────────────────────────────────
create policy "plats_select_public" on public.plats
  for select using (true);

create policy "plats_admin_insert" on public.plats
  for insert
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

create policy "plats_admin_update" on public.plats
  for update
  using   (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

create policy "plats_admin_delete" on public.plats
  for delete
  using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

-- ── Profils ───────────────────────────────────────────────────────────────────
create policy "profiles_select_own" on public.profiles
  for select using (auth.uid() = id);

create policy "profiles_update_own" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "profiles_insert_own" on public.profiles
  for insert with check (auth.uid() = id);

-- ── Commandes ─────────────────────────────────────────────────────────────────
create policy "commandes_select" on public.commandes
  for select using (
    user_id = auth.uid()
    or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

create policy "commandes_insert" on public.commandes
  for insert with check (auth.uid() = user_id);

create policy "commandes_update_admin" on public.commandes
  for update
  using   (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'))
  with check (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin'));

-- ── Lignes de commande ────────────────────────────────────────────────────────
create policy "commande_items_select" on public.commande_items
  for select using (
    exists (
      select 1 from public.commandes c
      where c.id = commande_id
      and (
        c.user_id = auth.uid()
        or exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
      )
    )
  );

create policy "commande_items_insert" on public.commande_items
  for insert with check (
    exists (
      select 1 from public.commandes c
      where c.id = commande_id and c.user_id = auth.uid()
    )
  );

-- ── Push tokens ───────────────────────────────────────────────────────────────
create policy "push_tokens_own_all" on public.push_tokens
  for all
  using   (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- ── Avis ──────────────────────────────────────────────────────────────────────
create policy "avis_select_public" on public.avis
  for select using (true);

create policy "avis_insert_own" on public.avis
  for insert with check (auth.uid() = user_id);

create policy "avis_update_own" on public.avis
  for update using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "avis_delete_own" on public.avis
  for delete using (auth.uid() = user_id);

-- ── Favoris ───────────────────────────────────────────────────────────────────
create policy "favoris_select_own" on public.favoris
  for select using (auth.uid() = user_id);

create policy "favoris_insert_own" on public.favoris
  for insert with check (auth.uid() = user_id);

create policy "favoris_delete_own" on public.favoris
  for delete using (auth.uid() = user_id);


-- =============================================================================
-- 6. STORAGE — Bucket « plats » + politiques
-- =============================================================================

insert into storage.buckets (id, name, public)
values ('plats', 'plats', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "plats_storage_public_read"   on storage.objects;
drop policy if exists "plats_storage_admin_insert"  on storage.objects;
drop policy if exists "plats_storage_admin_update"  on storage.objects;
drop policy if exists "plats_storage_admin_delete"  on storage.objects;

-- Lecture publique (CDN)
create policy "plats_storage_public_read" on storage.objects
  for select using (bucket_id = 'plats');

-- Écriture réservée aux admins
create policy "plats_storage_admin_insert" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'plats'
    and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

create policy "plats_storage_admin_update" on storage.objects
  for update to authenticated
  using (
    bucket_id = 'plats'
    and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  )
  with check (
    bucket_id = 'plats'
    and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );

create policy "plats_storage_admin_delete" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'plats'
    and exists (select 1 from public.profiles p where p.id = auth.uid() and p.role = 'admin')
  );


-- =============================================================================
-- 7. DONNÉES INITIALES — Menu luxe
--
-- Prérequis : uploader les images dans Storage → bucket "plats" → dossier "covers"
--   tagliatelles_homard.webp, risotto_truffe.jpg, steak_wagyu.webp,
--   foie_gras_poele.jpg, jus_mangue_passion.webp, jus_detox_vert.webp
-- La pizza utilise l'image existante à la racine du bucket (plats.jpg).
-- =============================================================================

insert into public.categories (nom, emoji) values
  ('Pizzas',           '🍕'),
  ('Pâtes & Risottos', '🍝'),
  ('Viandes Premium',  '🥩'),
  ('Sushis',           '🍣'),
  ('Boissons',         '🥤');

-- Pizzas
insert into public.plats (nom, description, prix, image_url, categorie_id)
select 'Pizza gourmande à la truffe',
       'Pizza à la crème de truffe, mozzarella di bufala et truffe noire.',
       120,
       'https://wlrcoqdetwgjvarrmftl.supabase.co/storage/v1/object/public/plats/plats.jpg',
       c.id
from public.categories c where c.nom = 'Pizzas' limit 1;

-- Pâtes & Risottos
insert into public.plats (nom, description, prix, image_url, categorie_id)
select 'Tagliatelles au homard',
       'Pâtes fraîches avec sauce crémeuse au homard, parfumée au cognac.',
       180,
       'https://wlrcoqdetwgjvarrmftl.supabase.co/storage/v1/object/public/plats/covers/tagliatelles_homard.webp',
       c.id
from public.categories c where c.nom = 'Pâtes & Risottos' limit 1;

insert into public.plats (nom, description, prix, image_url, categorie_id)
select 'Risotto à la truffe',
       'Riz arborio crémeux au parmesan, beurre et truffe noire.',
       160,
       'https://wlrcoqdetwgjvarrmftl.supabase.co/storage/v1/object/public/plats/covers/risotto_truffe.jpg',
       c.id
from public.categories c where c.nom = 'Pâtes & Risottos' limit 1;

-- Viandes Premium
insert into public.plats (nom, description, prix, image_url, categorie_id)
select 'Steak de wagyu',
       'Bœuf japonais très tendre et marbré, considéré comme un produit de luxe.',
       400,
       'https://wlrcoqdetwgjvarrmftl.supabase.co/storage/v1/object/public/plats/covers/steak_wagyu.webp',
       c.id
from public.categories c where c.nom = 'Viandes Premium' limit 1;

insert into public.plats (nom, description, prix, image_url, categorie_id)
select 'Foie gras poêlé',
       'Foie gras chaud servi avec une sauce sucrée (figues, balsamique ou fruits rouges).',
       150,
       'https://wlrcoqdetwgjvarrmftl.supabase.co/storage/v1/object/public/plats/covers/foie_gras_poele.jpg',
       c.id
from public.categories c where c.nom = 'Viandes Premium' limit 1;

-- Sushis
insert into public.plats (nom, description, prix, image_url, categorie_id)
select 'Sushi Omakase',
       'Dégustation japonaise où le chef sélectionne des sushis premium du jour.',
       500,
       null,
       c.id
from public.categories c where c.nom = 'Sushis' limit 1;

-- Boissons
insert into public.plats (nom, description, prix, image_url, categorie_id)
select 'Jus mangue–fruit de la passion',
       'Jus exotique épais et frais à base de mangue et fruit de la passion.',
       40,
       'https://wlrcoqdetwgjvarrmftl.supabase.co/storage/v1/object/public/plats/covers/jus_mangue_passion.webp',
       c.id
from public.categories c where c.nom = 'Boissons' limit 1;

insert into public.plats (nom, description, prix, image_url, categorie_id)
select 'Jus detox vert gourmet',
       'Jus frais à base de concombre, pomme verte, céleri, citron et menthe.',
       35,
       'https://wlrcoqdetwgjvarrmftl.supabase.co/storage/v1/object/public/plats/covers/jus_detox_vert.webp',
       c.id
from public.categories c where c.nom = 'Boissons' limit 1;


-- =============================================================================
-- 8. NOTES DE CONFIGURATION (post-exécution)
--
-- a) Compte administrateur :
--    Après inscription, exécuter :
--    update public.profiles set role = 'admin' where email = 'ton@email.com';
--
-- b) Images des plats :
--    Uploader dans Storage → bucket "plats" → dossier "covers" les fichiers :
--    tagliatelles_homard.webp  /  risotto_truffe.jpg  /  steak_wagyu.webp
--    foie_gras_poele.jpg       /  jus_mangue_passion.webp  /  jus_detox_vert.webp
--    (La pizza utilise l'image déjà présente : plats.jpg à la racine du bucket)
-- =============================================================================
